name: PyPI
on:
  push:
    branches:
      - main
      - develop
jobs:
  pypi:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      package: "${{ github.event.repository.name }}"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install bump2version
        run: pip install bump2version

      - name: Print version
        run: python setup.py --version

      - name: Print SHA
        run: echo ${GITHUB_SHA::8}

      - name: Bump version
        run: |
          bump2version sha --no-commit --allow-dirty \
          --new-version "$(python setup.py --version)-dev${GITHUB_SHA::8}"

      - uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          build: true
          upload: true
